name: Continuous Integration

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - production

jobs:
  test:
    name: Ensure that every tests passes and the build has the expected files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        run: make test
      - name: Example
        run: make example-build
